inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/IndexedLet:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space