inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - _site/**/*
    - node_modules/**/*
    - vendor/**/*
    - bin/bundle
    - config/*
    - db/**/*


Lint/ShadowingOuterLocalVariable:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/Documentation:
  Exclude:
    - app/controllers/application_controller.rb
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - test/application_system_test_case.rb
    - test/test_helper.rb